# Generated by Django 5.1 on 2024-08-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advanced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=200)),
                ('datestamp', models.CharField(max_length=200)),
                ('sun_sunrise_timestamp', models.CharField(max_length=200)),
                ('sun_sunset_timestamp', models.CharField(max_length=200)),
                ('sun_solar_noon', models.CharField(max_length=200)),
                ('sun_day_length', models.CharField(max_length=200)),
                ('sun_altitude', models.CharField(max_length=200)),
                ('sun_distance', models.CharField(max_length=200)),
                ('sun_azimuth', models.CharField(max_length=200)),
                ('sun_next_solar_eclipse_timestamp', models.CharField(max_length=200)),
                ('sun_next_solar_eclipse_datestamp', models.CharField(max_length=200)),
                ('sun_next_solar_eclipse_type', models.CharField(max_length=200)),
                ('sun_next_solar_eclipse_visibility_regions', models.CharField(max_length=200)),
                ('moon_type', models.CharField(max_length=200)),
                ('moon_phase_type', models.CharField(max_length=200)),
                ('moon_phase_name', models.CharField(max_length=200)),
                ('moon_phase_stage', models.CharField(max_length=200)),
                ('moon_phase_illumination', models.CharField(max_length=200)),
                ('moon_phase_age_days', models.CharField(max_length=200)),
                ('moon_phase_emoji', models.CharField(max_length=200)),
                ('moon_phase_zodiac_type', models.CharField(max_length=200)),
                ('moon_phase_zodiac_sun_sign', models.CharField(max_length=200)),
                ('moon_phase_zodiac_moon_sign', models.CharField(max_length=200)),
                ('moon_moonrise_type', models.CharField(max_length=200)),
                ('moon_moonrise_timestamp', models.CharField(max_length=200)),
                ('moon_moonset_timestamp', models.CharField(max_length=200)),
                ('moon_moon_altitude', models.CharField(max_length=200)),
                ('moon_moon_distance', models.CharField(max_length=200)),
                ('moon_moon_azimuth', models.CharField(max_length=200)),
                ('moon_moon_parallactic_angle', models.CharField(max_length=200)),
                ('moon_next_lunar_eclipse_type', models.CharField(max_length=200)),
                ('moon_next_lunar_eclipse_timestamp', models.CharField(max_length=200)),
                ('moon_next_lunar_eclipse_datestamp', models.CharField(max_length=200)),
                ('moon_next_lunar_eclipse_visibility_regions', models.CharField(max_length=200)),
                ('moon_moon_phase_type', models.CharField(max_length=200)),
                ('moon_moon_phase_new_moon_type', models.CharField(max_length=200)),
                ('moon_moon_phase_new_moon_last', models.CharField(max_length=200)),
                ('moon_moon_phase_new_moon_last_timestamp', models.CharField(max_length=200)),
                ('moon_moon_phase_new_moon_last_datestamp', models.CharField(max_length=200)),
                ('moon_moon_phase_new_moon_last_days_ago', models.CharField(max_length=200)),
                ('moon_moon_phase_new_moon_next', models.CharField(max_length=200)),
                ('moon_moon_phase_new_moon_next_timestamp', models.CharField(max_length=200)),
                ('moon_moon_phase_new_moon_next_datestamp', models.CharField(max_length=200)),
                ('moon_moon_phase_new_moon_next_days_ahead', models.CharField(max_length=200)),
                ('moon_moon_phase_full_moon_last_type', models.CharField(max_length=200)),
                ('moon_moon_phase_full_moon_last_last', models.CharField(max_length=200)),
                ('moon_moon_phase_full_moon_last_timestamp', models.CharField(max_length=200)),
                ('moon_moon_phase_full_moon_last_datestamp', models.CharField(max_length=200)),
                ('moon_moon_phase_full_moon_last_days_ago', models.CharField(max_length=200)),
                ('moon_moon_phase_full_moon_last_name', models.CharField(max_length=200)),
                ('moon_moon_phase_full_moon_last_description', models.CharField(max_length=200)),
                ('moon_moon_phase_full_moon_next_type', models.CharField(max_length=200)),
                ('moon_moon_phase_full_moon_next_next', models.CharField(max_length=200)),
                ('moon_moon_phase_full_moon_next_timestamp', models.CharField(max_length=200)),
                ('moon_moon_phase_full_moon_next_datestamp', models.CharField(max_length=200)),
                ('moon_moon_phase_full_moon_next_days_ahead', models.CharField(max_length=500)),
                ('moon_moon_phase_full_moon_next_name', models.CharField(max_length=200)),
                ('moon_moon_phase_full_moon_next_description', models.CharField(max_length=500)),
                ('location_latitude', models.CharField(max_length=200)),
                ('location_longitude', models.CharField(max_length=200)),
            ],
        ),
    ]
