# Generated by Django 5.1 on 2024-09-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_advanced_moon_moon_phase_full_moon_last_last_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanced',
            name='moon_moonrise_timestamp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='advanced',
            name='moon_moonset_timestamp',
            field=models.CharField(max_length=20),
        ),
    ]
