from django.db import models


class Advanced(models.Model):
    timestamp = models.IntegerField()
    datestamp = models.CharField(max_length=200)
    sun_sunrise_timestamp = models.IntegerField()
    sun_sunset_timestamp = models.IntegerField()
    sun_solar_noon = models.CharField(max_length=200)
    sun_day_length = models.CharField(max_length=200)
    sun_altitude = models.FloatField()
    sun_distance = models.FloatField()
    sun_azimuth = models.FloatField()
    sun_next_solar_eclipse_timestamp = models.IntegerField()
    sun_next_solar_eclipse_datestamp = models.CharField(max_length=200)
    sun_next_solar_eclipse_type = models.CharField(max_length=200)
    sun_next_solar_eclipse_visibility_regions = models.CharField(max_length=200)
    moon_phase_type = models.FloatField()
    moon_phase_name = models.CharField(max_length=200)
    moon_phase_stage = models.CharField(max_length=200)
    moon_phase_illumination = models.CharField(max_length=10)
    moon_phase_age_days = models.IntegerField()
    moon_phase_lunar_cycle = models.CharField(max_length=10, null=True)
    moon_phase_emoji = models.CharField(max_length=1)
    moon_phase_zodiac_sun_sign = models.CharField(max_length=200)
    moon_phase_zodiac_moon_sign = models.CharField(max_length=200)
    moon_moonrise_timestamp = models.IntegerField()
    moon_moonset_timestamp = models.IntegerField()
    moon_moon_altitude = models.FloatField()
    moon_moon_distance = models.FloatField()
    moon_moon_azimuth = models.FloatField()
    moon_moon_parallactic_angle = models.FloatField()
    moon_next_lunar_eclipse_timestamp = models.IntegerField()
    moon_next_lunar_eclipse_datestamp = models.CharField(max_length=200)
    moon_moon_phase_type = models.CharField(max_length=200)
    moon_next_lunar_eclipse_visibility_regions = models.CharField(max_length=200)
    moon_moon_phase_new_moon_last_timestamp = models.IntegerField()
    moon_moon_phase_new_moon_last_datestamp = models.CharField(max_length=200)
    moon_moon_phase_new_moon_last_days_ago = models.IntegerField()
    moon_moon_phase_new_moon_next_timestamp = models.IntegerField
    moon_moon_phase_new_moon_next_datestamp = models.CharField(max_length=200)
    moon_moon_phase_new_moon_next_days_ahead = models.IntegerField()
    moon_moon_phase_full_moon_last_timestamp = models.IntegerField()
    moon_moon_phase_full_moon_last_datestamp = models.CharField(max_length=200)
    moon_moon_phase_full_moon_last_days_ago = models.IntegerField()
    moon_moon_phase_full_moon_last_name = models.CharField(max_length=200)
    moon_moon_phase_full_moon_last_description = models.CharField(max_length=200)
    moon_moon_phase_full_moon_next_timestamp = models.IntegerField()
    moon_moon_phase_full_moon_next_datestamp = models.CharField(max_length=200)
    moon_moon_phase_full_moon_next_days_ahead = models.IntegerField()
    moon_moon_phase_full_moon_next_name = models.CharField(max_length=200)
    moon_moon_phase_full_moon_next_description = models.CharField(max_length=500)
    location_latitude = models.FloatField()
    location_longitude = models.FloatField()
